### ISSUE TITLE
exe安装包下载、安装、打开报警告

### ISSUE THREAD

**Issue by YaleJian** [team-ide/teamide#106]
下载x86 exe安装包：TeamIDE-windows-x64-1.5.1.exe
浏览器有以下警告：
![image](https://user-images.githubusercontent.com/17241277/181446412-c2772278-6821-44a9-81fd-45bd50a47583.png)

安装时操作系统提示：
![image](https://user-images.githubusercontent.com/17241277/181447644-f3f24785-bb4e-4cc6-b90c-8a81f276e945.png)

打开软件时有网络提示：
![image](https://user-images.githubusercontent.com/17241277/181447991-0273745a-698b-4851-9d3c-7fb724b4fefa.png)

环境：
chrome 版本 103.0.5060.114（正式版本） （64 位）
windows 11 22H2

**Comment by team-ide** [comment]
因为打包的window程序没有证书 所有不受信
