### ISSUE TITLE
MAC 版本空白页面

### ISSUE THREAD

**Issue by mazhenguo** [team-ide/teamide#109]
1.8.7版本  MAC下载后，版本是v1.0.0的版本，且打开以后是空白页面。
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/4089199/206901089-a9020b7f-3da0-4cf7-a219-48c90f8f8522.png">

**Comment by team-ide** [comment]
你看下 用户目录/TeamIDE/log 下边 日志 有没有错误

**Comment by mazhenguo** [comment]
{"level":"error","time":"2022-12-11 19:18:28.480","caller":"teamide/main.go:112","msg":"启动失败","error":"runtime error: invalid memory address or nil pointer dereference"}

**Comment by 63777887** [comment]
V1.8.7我Mac正常打开啊
<img width="1440" alt="teamIde" src="https://user-images.githubusercontent.com/56616254/206946895-1cde81e8-7b19-4fda-840f-2dda94aeec10.png">

**Comment by mazhenguo** [comment]
我这里不行，错误日志如上。我的系统版本是：
<img width="472" alt="image" src="https://user-images.githubusercontent.com/4089199/206949237-f1c0cf62-62d2-4549-ba6b-0924f36adf8c.png">

**Comment by team-ide** [comment]
这个异常上边的日志还有吗

**Comment by mazhenguo** [comment]
这个是报错日志，需要要全量的错误日志吗？

**Comment by mazhenguo** [comment]
{"level":"info","time":"2022-12-12 13:01:05.313","caller":"context/decryption.go:102","msg":"服务器加密成功!"}
{"level":"info","time":"2022-12-12 13:01:05.314","caller":"context/decryption.go:109","msg":"服务器解密成功!"}
{"level":"info","time":"2022-12-12 13:01:05.314","caller":"context/decryption.go:117","msg":"服务器加密验证成功!"}
{"level":"info","time":"2022-12-12 13:01:05.314","caller":"context/decryption.go:124","msg":"服务器解密验证成功!"}
{"level":"warn","time":"2022-12-12 13:01:05.314","caller":"module/api.go:71","msg":"权限[toolbox]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.314","caller":"module/api.go:71","msg":"权限[toolbox/group]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.314","caller":"module/api.go:71","msg":"权限[toolbox/quickCommand]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.314","caller":"module/api.go:71","msg":"权限[database]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.314","caller":"module/api.go:71","msg":"权限[elasticsearch]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.314","caller":"module/api.go:71","msg":"权限[node]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.314","caller":"module/api.go:71","msg":"权限[node/system]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.315","caller":"module/api.go:71","msg":"权限[node/netProxy]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.315","caller":"module/api.go:71","msg":"权限[kafka]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.315","caller":"module/api.go:71","msg":"权限[log]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.315","caller":"module/api.go:71","msg":"权限[user]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.315","caller":"module/api.go:71","msg":"权限[power]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.315","caller":"module/api.go:71","msg":"权限[redis]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.315","caller":"module/api.go:71","msg":"权限[terminal]未配置动作"}
{"level":"warn","time":"2022-12-12 13:01:05.315","caller":"module/api.go:71","msg":"权限[zookeeper]未配置动作"}
{"level":"info","time":"2022-12-12 13:01:05.438","caller":"web/web.go:87","msg":"http server start","addr":"0.0.0.0:60574"}
{"level":"info","time":"2022-12-12 13:01:05.539","caller":"web/web.go:106","msg":"监听服务是否启动成功","checkURL":"http://localhost:60574/"}
{"level":"error","time":"2022-12-12 13:01:05.553","caller":"teamide/main.go:112","msg":"启动失败","error":"runtime error: invalid memory address or nil pointer dereference"}

**Comment by mazhenguo** [comment]
以上是启动的全量日志

**Comment by team-ide** [comment]
你试下最新版本，看看能否启动成功

**Comment by mazhenguo** [comment]
页面可以打开了，但日志中还是报错。


{"level":"info","time":"2022-12-12 17:09:55.512","caller":"context/decryption.go:102","msg":"服务器加密成功!"}
{"level":"info","time":"2022-12-12 17:09:55.513","caller":"context/decryption.go:109","msg":"服务器解密成功!"}
{"level":"info","time":"2022-12-12 17:09:55.513","caller":"context/decryption.go:117","msg":"服务器加密验证成功!"}
{"level":"info","time":"2022-12-12 17:09:55.513","caller":"context/decryption.go:124","msg":"服务器解密验证成功!"}
{"level":"info","time":"2022-12-12 17:09:55.513","caller":"teamide/main.go:176","msg":"context init success"}
{"level":"info","time":"2022-12-12 17:09:55.513","caller":"teamide/main.go:177","msg":"server to start"}
{"level":"info","time":"2022-12-12 17:09:55.527","caller":"web/web.go:87","msg":"http server start","addr":"0.0.0.0:53593"}
{"level":"info","time":"2022-12-12 17:09:55.628","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:55.638","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:55.739","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:55.741","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:55.841","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:55.843","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:55.944","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:55.947","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:56.048","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:56.051","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:56.151","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:56.154","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:56.254","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:56.257","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:56.358","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:56.361","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:56.462","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:56.464","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:56.565","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:56.568","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:56.668","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:56.671","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:56.771","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:56.774","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:56.875","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:56.877","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:56.978","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:56.980","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:57.080","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:57.082","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:57.183","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:57.186","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:57.287","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:57.290","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:57.391","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:57.394","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:57.495","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:57.498","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:57.599","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:57.602","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:57.703","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:57.706","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:57.807","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:57.810","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:57.911","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:57.914","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:58.015","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:58.017","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:58.118","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:58.121","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:58.222","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:58.224","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:58.325","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:58.328","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:58.429","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:58.432","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:58.533","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:58.536","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:58.637","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:58.640","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:58.741","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:58.744","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:58.845","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:58.848","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:58.949","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:58.952","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:59.053","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:59.056","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:59.156","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:59.159","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:59.259","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:59.262","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:59.363","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:59.366","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:59.467","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:59.470","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:59.571","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:59.574","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:59.675","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:59.678","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:59.779","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:59.782","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:59.883","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:59.885","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:09:59.986","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:09:59.989","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:10:00.090","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:10:00.093","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:10:00.194","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:10:00.197","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:10:00.298","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:10:00.301","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:10:00.402","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:10:00.405","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:10:00.507","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:10:00.509","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"info","time":"2022-12-12 17:10:00.610","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:53593/"}
{"level":"warn","time":"2022-12-12 17:10:00.613","caller":"web/web.go:115","msg":"监听服务连接失败，将继续监听","checkURL":"http://localhost:53593/","error":"Get \"http://localhost:53593/\": dial tcp: lookup localhost: no such host"}
{"level":"warn","time":"2022-12-12 17:10:00.613","caller":"web/web.go:107","msg":"服务启动检查超过5秒，不再检测"}
{"level":"info","time":"2022-12-12 17:10:00.613","caller":"teamide/main.go:183","msg":"server start success"}
{"level":"info","time":"2022-12-12 17:10:01.179","caller":"module/api.go:234","msg":"处理操作","action":"data"}
{"level":"info","time":"2022-12-12 17:10:01.280","caller":"module/api.go:234","msg":"处理操作","action":"session"}
{"level":"info","time":"2022-12-12 17:10:01.290","caller":"module/api.go:234","msg":"处理操作","action":"websocket"}
{"level":"info","time":"2022-12-12 17:10:01.332","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/count"}
{"level":"info","time":"2022-12-12 17:10:01.332","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/list"}
{"level":"info","time":"2022-12-12 17:10:01.333","caller":"module/api.go:234","msg":"处理操作","action":"node/list"}
{"level":"info","time":"2022-12-12 17:10:01.333","caller":"module/api.go:234","msg":"处理操作","action":"updateCheck"}
{"level":"info","time":"2022-12-12 17:10:01.335","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/queryOpens"}
{"level":"info","time":"2022-12-12 17:10:01.368","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/count"}
{"level":"info","time":"2022-12-12 17:10:01.369","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/list"}
{"level":"info","time":"2022-12-12 17:10:01.369","caller":"module/api.go:234","msg":"处理操作","action":"node/list"}
{"level":"info","time":"2022-12-12 17:10:01.370","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/group/list"}
{"level":"info","time":"2022-12-12 17:10:01.380","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/list"}

**Comment by team-ide** [comment]
你本地 localhost 回路是不是没有 用这个访问好像不行 页面能正常使用吗

**Comment by team-ide** [comment]
看下 hosts文件里边 有没有 `127.0.0.1 localhost` 这样的配置 如果没有可以加一个 Team IDE 本地程序使用的是 localhost:port 访问

**Comment by mazhenguo** [comment]
hosts文件中加了        127.0.0.1 localhost   就可以了


{"level":"info","time":"2022-12-12 17:51:17.331","caller":"context/decryption.go:102","msg":"服务器加密成功!"}
{"level":"info","time":"2022-12-12 17:51:17.334","caller":"context/decryption.go:109","msg":"服务器解密成功!"}
{"level":"info","time":"2022-12-12 17:51:17.334","caller":"context/decryption.go:117","msg":"服务器加密验证成功!"}
{"level":"info","time":"2022-12-12 17:51:17.335","caller":"context/decryption.go:124","msg":"服务器解密验证成功!"}
{"level":"info","time":"2022-12-12 17:51:17.335","caller":"teamide/main.go:176","msg":"context init success"}
{"level":"info","time":"2022-12-12 17:51:17.335","caller":"teamide/main.go:177","msg":"server to start"}
{"level":"info","time":"2022-12-12 17:51:17.367","caller":"web/web.go:87","msg":"http server start","addr":"0.0.0.0:54818"}
{"level":"info","time":"2022-12-12 17:51:17.468","caller":"web/web.go:112","msg":"监听服务是否启动成功","checkURL":"http://localhost:54818/"}
{"level":"info","time":"2022-12-12 17:51:17.479","caller":"web/web.go:124","msg":"服务启动成功","ServerUrl":"http://localhost:54818"}
{"level":"info","time":"2022-12-12 17:51:17.479","caller":"teamide/main.go:183","msg":"server start success"}
{"level":"info","time":"2022-12-12 17:51:18.129","caller":"module/api.go:234","msg":"处理操作","action":"data"}
{"level":"info","time":"2022-12-12 17:51:18.230","caller":"module/api.go:234","msg":"处理操作","action":"session"}
{"level":"info","time":"2022-12-12 17:51:18.243","caller":"module/api.go:234","msg":"处理操作","action":"websocket"}
{"level":"info","time":"2022-12-12 17:51:18.302","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/count"}
{"level":"info","time":"2022-12-12 17:51:18.302","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/list"}
{"level":"info","time":"2022-12-12 17:51:18.303","caller":"module/api.go:234","msg":"处理操作","action":"node/list"}
{"level":"info","time":"2022-12-12 17:51:18.303","caller":"module/api.go:234","msg":"处理操作","action":"updateCheck"}
{"level":"info","time":"2022-12-12 17:51:18.304","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/queryOpens"}
{"level":"info","time":"2022-12-12 17:51:18.339","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/count"}
{"level":"info","time":"2022-12-12 17:51:18.340","caller":"module/api.go:234","msg":"处理操作","action":"node/list"}
{"level":"info","time":"2022-12-12 17:51:18.341","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/group/list"}
{"level":"info","time":"2022-12-12 17:51:18.341","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/list"}
{"level":"info","time":"2022-12-12 17:51:18.367","caller":"module/api.go:234","msg":"处理操作","action":"toolbox/list"}

**Comment by mazhenguo** [comment]
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/4089199/207015991-3de107cd-cab8-4390-b877-9b6cb904c6a9.png">

**Comment by team-ide** [comment]
SQL 执行 结果展示 目前是 select、show处理结果集 后边这些也补充下
