### ISSUE TITLE
SSH bug,MobaXterm和xshell 7可以登录，这个工具不行

### ISSUE THREAD

**Issue by Asura88** [team-ide/teamide#113]
SSH bug,MobaXterm和xshell 7可以登录，这个工具不行

**Comment by team-ide** [comment]
有错误信息吗  
还有 看下 用户目录 下的 TeamIDE\log\server.log 日志 是否有错误信息

**Comment by team-ide** [comment]
![image](https://github.com/team-ide/teamide/assets/75514614/96dd05cc-fc31-4aaf-b571-035e5d011f91)

看不到有效信息

**Comment by Asura88** [comment]
解决了，工具没有默认端口，建议设置默认22，客户没有输入端口导致连接失败




努力奋进的机械人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "team-ide/teamide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月23日(星期二) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [team-ide/teamide] SSH bug,MobaXterm和xshell 7可以登录，这个工具不行 (Issue #113)





 
有错误信息吗
 还有 看下 用户目录 下的 TeamIDE\log\server.log 日志 是否有错误信息

**Comment by team-ide** [comment]
ok
