### ISSUE TITLE
软件后台运行后有外联

### ISSUE THREAD

**Issue by Asura88** [team-ide/teamide#115]
软件后台运行后有外联

<img width="488" alt="bc99b88492f8c46d9d6cdd35215932e" src="https://github.com/team-ide/teamide/assets/25000885/a6224e6c-6a7e-4b48-beb2-18223ffd3422">

**Comment by team-ide** [comment]
teamide 会到 GitHub或gitee检查更新，用于页面展示是否有新版本，你可以看下 ip 是否一致，没有其它网络请求
