### ISSUE TITLE
ssh连接超时时间可配置自动心跳或者配置超时时间

### ISSUE THREAD

**Issue by ixxxk** [team-ide/teamide#123]
1、设置中配置是否自动心跳，配置自动心跳时间
2、配置中可手动配置中断操作时间
提此issue的原因如下：
    现在只有固定1分钟未操作即中断会话，很多时候会影响到现有操作，如回头看了一眼东西，或者寻找一些命令和解决方案再操作，却发现已中断操作，并且重新连接又回到root下了，而非当前目录，体验不好。

**Comment by team-ide** [comment]
可以看下 `2.4.3` 版本是否能满足需求，建议修改服务端 TMOUT 来解决超时问题，毕竟发送自定义字符容易打乱命令

**Comment by ixxxk** [comment]
感谢作者大大，有求必应的感觉真好。
