### ISSUE TITLE
docker部署无法使用SSH

### ISSUE THREAD

**Issue by gstory0404** [team-ide/teamide#128]
docker部署后链接SSH报错误，提示 终端会话已关闭，输入回车重新连接！

**Comment by team-ide** [comment]
我这边测试是可以使用的，你进入容器中到 `/opt/teamide/log` ，看下 `server.log` 日志，是否有异常日志

**Comment by team-ide** [comment]
你访问Team IDE是直接访问 还是通过nginx代理的，如果是nginx代码 需要添加支持 websocket的配置

**Comment by gstory0404** [comment]
好的 确实是由于没有打开websocket导致的 感谢
