### ISSUE TITLE
Windows下cmd进程不结束

### ISSUE THREAD

**Issue by Hawkeyes0** [team-ide/teamide#138]
Windows环境下。
1. 终端标签关闭后，cmd.exe进程不退出。打开新终端页后，会启动新的cmd.exe进程
2. 当在本地终端连接中输入exit后，cmd.exe进程退出，但标签页不关闭

**Comment by team-ide** [comment]
试下  Version 2.4.5 （2023/11/1）

修复功能： Windows 新建本地终端，标签页关闭后命令行未关闭问题修复

标签页输入退出标签页不会自动关闭的，会保留页面状态方便回车重连

**Comment by Hawkeyes0** [comment]
修复确认。 谢谢
