### ISSUE TITLE
数据库Postgresql不能选SSH方式登录

### ISSUE THREAD

**Issue by jthb1** [team-ide/teamide#139]
![微信截图_20231031091634](https://github.com/team-ide/teamide/assets/12574728/72da40b8-be99-41e1-89c9-0875a8f0c0b1)
新增Database工具可以选择ssh节点，数据库类型选Postgresql之后，ssh节点就不见了，也不能测试成功。

**Comment by team-ide** [comment]
可以试下 2.4.7 版本 添加了几种数据库 SSH支持
