### ISSUE TITLE
希望支持mysql查询界面数据的保存

### ISSUE THREAD

**Issue by yyl-test** [team-ide/teamide#141]
![Snipaste_2023-10-31_18-17-10](https://github.com/team-ide/teamide/assets/49875523/85f249a5-5c16-4d3a-b7d4-61900fc68fe5)

**Comment by team-ide** [comment]
可以试下新版本 支持数据列表数据导出

**Comment by yyl-test** [comment]
不好意思 可能是我描述的不是很清析

我的意思是可能有一些个人常用的sql查询命令，是不是可以手动/自动保存查询语句到某个目录下，不然每次都要从别的地方把sql复制过来

**Comment by team-ide** [comment]
有时间 可以试下新版本 可以上传SQL 并且记录历史保存的SQL文件  目前不能修改名称后续会添加
