### ISSUE TITLE
数据库连接使用体验优化

### ISSUE THREAD

**Issue by change41** [team-ide/teamide#143]
版本：[2.4.6](https://github.com/team-ide/teamide/releases/tag/v2.4.6)
数据库类型：mysql 

![image](https://github.com/team-ide/teamide/assets/29248210/0849236d-9fe3-4c68-a193-78673e78ee09)

![image](https://github.com/team-ide/teamide/assets/29248210/6634ee56-9cf7-4fc4-b32e-893a5c55aa2a)

语句查询和直接打开表查看都是一样的。希望能力能格式化日期显示，类型这种
![image](https://github.com/team-ide/teamide/assets/29248210/e912fc1b-d515-4b14-a75b-694733c08dfc)

另一个问题：
创建连接的时候已经设置了 database，连接后查询还需要再选择一次，使用上不是很友好 
![image](https://github.com/team-ide/teamide/assets/29248210/e80cfdc8-30bc-4b32-a5d6-b8643785533d)

**Comment by team-ide** [comment]
新版本中添加了日期格式化，数据库的话会将默认配置的库放到最上边，其他可见的库还是会展示在那
