### ISSUE TITLE
elastic有数据，但列表为空

### ISSUE THREAD

**Issue by eanliu-cn** [team-ide/teamide#156]
![image](https://github.com/team-ide/teamide/assets/71619270/a93513ff-a8af-4617-9a03-a62c9e95b90a)
![image](https://github.com/team-ide/teamide/assets/71619270/92786480-5220-4b06-bf55-6b034a23b92a)

存在子对象时，列表有数据但不显示

**Comment by team-ide** [comment]
有时间试下新版本 修复了这个问题

**Comment by eanliu-cn** [comment]
已更新，感谢！
