### ISSUE TITLE
文件管理器强烈建议增加一个鼠标右键上传文件的功能

### ISSUE THREAD

**Issue by Nodewebzsz** [team-ide/teamide#163]
文件管理器强烈建议增加一个鼠标右键上传文件的功能，这样操作更简单，还有mac点击终端->本地  ，无法输入命令，输入一个字符就自动换行了

**Comment by team-ide** [comment]
可以试下新版本 添加了右击上传  mac使用bash打开终端 zsh适配有问题暂时不用了
