### ISSUE TITLE
Docer部署，x86服务器，Oracle数据库连接报错

### ISSUE THREAD

**Issue by sifanx** [team-ide/teamide#165]
Docer部署，x86服务器，Oracle数据库连接报错
异常：ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help
![ide](https://github.com/team-ide/teamide/assets/42561369/3b428d69-2ca5-4ee3-9d42-56172f11c4ec)

我照着网上别人的方法，试过了，服务器也重启，还是不行
![ide2](https://github.com/team-ide/teamide/assets/42561369/eae0a06c-112f-4ffe-8ebc-8cc48102e910)

**Comment by team-ide** [comment]
有时间更新下最新镜像试下，之前镜像默认没装Oracle相关库
![image](https://github.com/team-ide/teamide/assets/75514614/f58b5f76-c76b-4139-a048-936ba304afc4)

**Comment by sifanx** [comment]
v2.5.6 的镜像可以正常使用了，谢谢~
