### ISSUE TITLE
Linux系统里的文件名无法复制

### ISSUE THREAD

**Issue by sifanx** [team-ide/teamide#166]
新建用户后，创建了Linux服务器信息，通过网页SSH连进去以后，发现从外面是可以复制内容到Linux里的，但是从Linux里复制内容到粘贴板就不行，我就无法复制图片中的压缩包名称，不管是用CTRL+C，还是鼠标右键，都提示”复制失败，请允许访问剪贴板“，2.5.6、2.5.7版本都有这个问题。
![ide](https://github.com/team-ide/teamide/assets/42561369/ee64a4e3-9738-4727-bf62-18c2112299db)

**Comment by sifanx** [comment]
我是docker部署的，数据目录里没有conf文件夹呢
![ide](https://github.com/team-ide/teamide/assets/42561369/9ec5570e-5141-4dcf-985a-59d3d91c67ad)

**Comment by team-ide** [comment]
需要到容器里边修改，data目录映射的只是数据文件等，配置在容器内conf一个目录

**Comment by sifanx** [comment]
进入容器修改conf/config.yaml，浏览器用https访问，能够正常复制了，谢谢
![ide](https://github.com/team-ide/teamide/assets/42561369/fc0e4427-f7e3-4cd7-94e7-020ee7b42958)
