### ISSUE TITLE
docker镜像过大

### ISSUE THREAD

**Issue by LockiJiang** [team-ide/teamide#167]
大佬，镜像来下来发现有4.7个G，看了下history，基础镜像太多层了，是否可以优化一下；也没有找到你的基础镜像的Dockerfile，是否可以直接使用go的官方基础镜像就可以了？

**Comment by team-ide** [comment]
新版本镜像已经缩小了，之前用的是环境镜像作为基础，所以比较大

**Comment by LockiJiang** [comment]
赞
