### ISSUE TITLE
终端界面字符显示不全

### ISSUE THREAD

**Issue by Hawkeyes0** [team-ide/teamide#169]
当终端中横向显示内容较多时，最右侧字符会显示到视口之外
![微信截图_20231208184310](https://github.com/team-ide/teamide/assets/2275023/fe996a55-efe7-476c-b361-b755d28f1126)

**Comment by team-ide** [comment]
有时间可以试下新版本，看看是否还有遮挡问题

**Comment by Hawkeyes0** [comment]
确认修复
