### ISSUE TITLE
属实没看懂到底咋用？

### ISSUE THREAD

**Issue by baozitao** [team-ide/teamide#177]
麻烦规整下使用说明，让人下载以后即可使用，麻烦多这几个字，能大幅提什星星数。这个工具还需要服务端？？？？好奇怪的玩法，还有客户端？？？？
是BS/CS?

**Comment by team-ide** [comment]
个人使用直接下载客户端包就可以，团队使用可以下载部署到服务器使用，两种方式

![image](https://github.com/team-ide/teamide/assets/75514614/87116d42-8a81-4459-aaf9-b3f77b54eda3)

**Comment by baozitao** [comment]
请问如果我有arm64的客户端，好像没有对应的下载

**Comment by team-ide** [comment]
客户端包没有arm架构的，你可以根据 `.github/workflows/release.yml` 中打包步骤打个
