### ISSUE TITLE
未授权访问

### ISSUE THREAD

**Issue by dear-cell** [team-ide/teamide#178]
我使用的版本是：[TeamIDE-win-2.6.9.exe]
该程序每次启动都会启动一个随机端口的web服务并且没有鉴权就可以直接访问到
![image](https://github.com/team-ide/teamide/assets/72452338/f2f95764-39e6-4d7d-868c-a0df5f769832)

![image](https://github.com/team-ide/teamide/assets/72452338/517cca98-1983-4ed8-8662-bbed033bf816)

内网用户无鉴权即可访问：
![aa86d32b87130a80efb4dd58682e748](https://github.com/team-ide/teamide/assets/72452338/0ad9a90c-10e9-4483-8660-ecbf7be801a3)

找了一下公网上的相关资产都是存在登录验证的看样子使用的版本好像是：[teamide-server-amd64-2.6.9.zip]
希望大佬能增加一个验证或者能关掉这个web页面吗？我是做安全的对这方面也不是很懂

**Comment by team-ide** [comment]
好的，下个版本启动将使用127.0.0.1绑定服务端口，只能本地访问
