### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by Risingrode** [team-ide/teamide#185]
使用rz命令，上传文件的时候，经常卡在最后
![image](https://github.com/team-ide/teamide/assets/97512230/23ae0461-0bda-4bff-bb23-b9185907bdb8)

**Comment by Risingrode** [comment]
就直接不动了

**Comment by team-ide** [comment]
是哪个版本

**Comment by Risingrode** [comment]
> 是哪个版本

![image](https://github.com/team-ide/teamide/assets/97512230/f1ebce6d-9c64-4996-92c5-f82b92db1781)

**Comment by Risingrode** [comment]
就是卡到99%的时候，就要等1分钟左右，才ok

**Comment by team-ide** [comment]
![image](https://github.com/team-ide/teamide/assets/75514614/c3f70655-ad13-4b96-a521-ded715561b67)
试下新版本 老版本 rz 的流会先传到本地后台 时间计算不正确，新版本分片同步传输

**Comment by Risingrode** [comment]
行
